### ISSUE TITLE
after migrate return 

### ISSUE THREAD

**Issue by vahidalvandi** [nazmussakib44/laravel-react-starter-kit#1]
2024_12_03_101410_create_oauth_personal_access_clients_table .......................................... 6.28ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_personal_access_clients' already exists (Connection: mysql, SQL: create table `oauth_personal_access_clients` (`id` bigint unsigned not null auto_increment primary key, `client_id` char(36) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:813
    809▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    810▕                 );
    811▕             }
    812▕ 
  ➜ 813▕             throw new QueryException(
    814▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    815▕             );
    816▕         }
    817▕     }

      +9 vendor frames 

  10  database/migrations/2024_12_03_101410_create_oauth_personal_access_clients_table.php:14
      Illuminate\Support\Facades\Facade::__callStatic()
      +37 vendor frames 

  48  artisan:13
      Illuminate\Foundation\Application::handleCommand()

**Comment by nazmussakib44** [comment]
Not a big deal.  Table already exists in your database. You may bypass the error by updating the migrations table or command. Hope you fixed the issue. Let me know if you need any help.
